[2021-09-17 16:39:02,301]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.address`.
[2021-09-17 16:39:02,309]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.address` has been localized to `zh_CN`.
[2021-09-17 16:39:02,310]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.automotive`.
[2021-09-17 16:39:02,314]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.automotive`. Locale reset to `en_US` for this provider.
[2021-09-17 16:39:02,316]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.bank`.
[2021-09-17 16:39:02,319]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
[2021-09-17 16:39:02,320]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.barcode`.
[2021-09-17 16:39:02,321]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.barcode`. Locale reset to `en_US` for this provider.
[2021-09-17 16:39:02,322]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.color`.
[2021-09-17 16:39:02,325]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.color`. Locale reset to `en_US` for this provider.
[2021-09-17 16:39:02,326]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.company`.
[2021-09-17 16:39:02,330]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.company` has been localized to `zh_CN`.
[2021-09-17 16:39:02,331]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.credit_card`.
[2021-09-17 16:39:02,332]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.credit_card`. Locale reset to `en_US` for this provider.
[2021-09-17 16:39:02,333]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.currency`.
[2021-09-17 16:39:02,336]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.currency`. Locale reset to `en_US` for this provider.
[2021-09-17 16:39:02,337]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.date_time`.
[2021-09-17 16:39:02,341]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.date_time`. Locale reset to `en_US` for this provider.
[2021-09-17 16:39:02,341]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.file` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:39:02,342]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.geo`.
[2021-09-17 16:39:02,343]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.geo`. Locale reset to `en_US` for this provider.
[2021-09-17 16:39:02,344]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.internet`.
[2021-09-17 16:39:02,349]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.internet` has been localized to `zh_CN`.
[2021-09-17 16:39:02,350]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.isbn` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:39:02,350]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.job`.
[2021-09-17 16:39:02,354]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.job` has been localized to `zh_CN`.
[2021-09-17 16:39:02,355]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.lorem`.
[2021-09-17 16:39:02,357]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.lorem` has been localized to `zh_CN`.
[2021-09-17 16:39:02,358]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.misc`.
[2021-09-17 16:39:02,359]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.misc`. Locale reset to `en_US` for this provider.
[2021-09-17 16:39:02,360]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.person`.
[2021-09-17 16:39:02,368]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.person` has been localized to `zh_CN`.
[2021-09-17 16:39:02,369]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.phone_number`.
[2021-09-17 16:39:02,376]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.phone_number` has been localized to `zh_CN`.
[2021-09-17 16:39:02,377]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.profile` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:39:02,377]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.python` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:39:02,377]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.ssn`.
[2021-09-17 16:39:02,384]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.ssn` has been localized to `zh_CN`.
[2021-09-17 16:39:02,386]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.user_agent` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:39:02,386]-[login.py|__init__]-[line|67]-DEBUG   : 登录环境--->test
[2021-09-17 16:39:02,386]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: https://gcgateway-dev.dingyl.com/unify_users/user/get/phone/code
请求data: {"n": {"out_organ_id": "dinge1e0bb139cd52aa335c2f4657eb6378f", "phone": "17205434095", "project_id": "hrm", "notice_title": 120}, "a": {"source": "1"}, "v": {}}
[2021-09-17 16:39:02,390]-[connectionpool.py|_new_conn]-[line|971]-DEBUG   : Starting new HTTPS connection (1): gcgateway-dev.dingyl.com:443
[2021-09-17 16:39:02,681]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : https://gcgateway-dev.dingyl.com:443 "POST /unify_users/user/get/phone/code HTTP/1.1" 200 None
[2021-09-17 16:39:02,685]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': '5909c8a43d0e4b48850c3d2ebd8fa8aa'}, 'n': {'code_id': '161cd871944f44348687a2d153248319'}, 'r': {'message': '成功', 'result': '1', 'sub_code': '', 'sub_message': ''}}
[2021-09-17 16:39:02,688]-[login.py|is_true]-[line|111]-INFO    : 获取登录验证码成功
[2021-09-17 16:39:02,689]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: http://121.40.151.38:9082/unify_users/notice/job/send/message
请求data: None
[2021-09-17 16:39:02,697]-[connectionpool.py|_new_conn]-[line|227]-DEBUG   : Starting new HTTP connection (1): 121.40.151.38:9082
[2021-09-17 16:39:02,799]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : http://121.40.151.38:9082 "POST /unify_users/notice/job/send/message HTTP/1.1" 200 None
[2021-09-17 16:39:02,802]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': 'a67a965d0ab749b3ad786079a9e86fb1'}, 'r': {'message': '成功', 'result': '1', 'sub_code': '', 'sub_message': ''}}
[2021-09-17 16:39:02,803]-[login.py|is_true]-[line|111]-INFO    : 执行验证码发送任务成功
[2021-09-17 16:39:02,803]-[login.py|__init__]-[line|25]-DEBUG   : 登录环境--->test
[2021-09-17 16:39:02,804]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: https://hrmapitest.dingyl.com/hrm/user/rsa/public/key/query
请求data: {"n": {"user_code": "GC0200074603961341"}, "a": {"source": "1284"}, "v": {}}
[2021-09-17 16:39:02,811]-[connectionpool.py|_new_conn]-[line|971]-DEBUG   : Starting new HTTPS connection (1): hrmapitest.dingyl.com:443
[2021-09-17 16:39:02,945]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : https://hrmapitest.dingyl.com:443 "POST /hrm/user/rsa/public/key/query HTTP/1.1" 200 None
[2021-09-17 16:39:02,946]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': '78f3b624ed134f2082cafd6388a7ecb9'}, 'n': {'random_key': '96599835'}, 'r': {'message': '成功', 'result': '1', 'sub_code': '', 'sub_message': ''}}
[2021-09-17 16:39:02,946]-[login.py|is_true]-[line|111]-INFO    : 获取登录key成功
[2021-09-17 16:39:02,947]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: https://hrmapitest.dingyl.com/hrm/user/login
请求data: {"n": {"user_code": "GC0200074603961341", "user_pwd": "12b165a5f7ac00a837267837eb1d7185", "corp_id": "dinge1e0bb139cd52aa335c2f4657eb6378f"}, "a": {"source": "1284"}}
[2021-09-17 16:39:02,949]-[connectionpool.py|_new_conn]-[line|971]-DEBUG   : Starting new HTTPS connection (1): hrmapitest.dingyl.com:443
[2021-09-17 16:39:03,170]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : https://hrmapitest.dingyl.com:443 "POST /hrm/user/login HTTP/1.1" 200 None
[2021-09-17 16:39:03,171]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': '0800e8ada749408a9418e5df3c561982'}, 'n': {'expire_time': '2022-09-30', 'gc_ding_dept_id': [{'key': 'd9abe94d140045788184433f81fe6b92', 'value': '科教科'}], 'is_expire': '0', 'personal_template_id': 'b764a448cd5f48799e2f515ce698c73a', 'position_form_id': 'POSITION_FORM1', 'product_type': '试用套餐', 'require_form_id': 'ZPXQFORM1', 'role_type': '', 'session_id': '77a08cdc1af74f18873ad479322d2d55', 'user_avatar': 'https://static-legacy.dingtalk.com/media/lADPDgQ9wHhdLP7NA-DNAug_744_992.jpg', 'user_id': 'f3be3fc8357549d0be674469cc6416f8', 'user_name': '白刚3ggg', 'worker_job_form_id': '1221'}, 'r': {'message': '成功', 'result': '1', 'sub_code': '', 'sub_message': ''}}
[2021-09-17 16:39:03,171]-[login.py|is_true]-[line|111]-INFO    : 登录结果成功
[2021-09-17 16:39:03,172]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: https://gcgateway-dev.dingyl.com/unify_message/notice/message/query
请求data: {"n": {"user_name": "", "user_phone": "17205434095", "message_content": "", "send_type": "295"}, "a": {"source": "1284"}, "v": "77a08cdc1af74f18873ad479322d2d55", "f": {"indexpage": 1, "repaging": "1", "pagesize": 10}}
[2021-09-17 16:39:03,174]-[connectionpool.py|_new_conn]-[line|971]-DEBUG   : Starting new HTTPS connection (1): gcgateway-dev.dingyl.com:443
[2021-09-17 16:39:03,274]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : https://gcgateway-dev.dingyl.com:443 "POST /unify_message/notice/message/query HTTP/1.1" 200 None
[2021-09-17 16:39:03,276]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': 'd2637b1078b4412e8f700c782bad045b'}, 'r': {'message': '数据格式异常', 'result': '0', 'sub_all_message': '', 'sub_code': '0', 'sub_message': 'JSON parse error: syntax error, expect {, actual string, pos 127, fieldName v, fastjson-version 1.2.71; nested exception is com.alibaba.fastjson.JSONException: syntax error, expect {, actual string, pos 127, fieldName v, fastjson-version 1.2.71'}}
